---
- name: Setup macOS Development Environment
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Ensure Homebrew is installed
      homebrew:
        state: present

    - name: Install Python
      homebrew:
        name: python
        state: present

    - name: Install VLC
      homebrew_cask:
        name: vlc
        state: present

    - name: Install DuckDuckGo
      homebrew_cask:
        name: duckduckgo
        state: present

    - name: Install Zoom
      homebrew_cask:
        name: zoom
        state: present

    - name: Install UTM
      homebrew_cask:
        name: utm
        state: present

    - name: Install Docker
      homebrew_cask:
        name: docker
        state: present

    - name: Install LM Studio
      homebrew_cask:
        name: lm-studio
        state: present
