---
- name: Install applications on macOS
  hosts: localhost
  connection: local
  tasks:
    - name: Install adobe-reader
      homebrew:
        name: adobe-reader
        state: present
      ignore_errors: true

    - name: Install dbeaver
      homebrew:
        name: dbeaver-community
        state: present
      ignore_errors: true

    - name: Install docker
      homebrew:
        name: docker
        state: present
      ignore_errors: true

    - name: Install gimp
      homebrew:
        name: gimp
        state: present
      ignore_errors: true

    - name: Install git
      homebrew:
        name: git
        state: present
      ignore_errors: true

    - name: Install libreoffice
      homebrew:
        name: libreoffice
        state: present
      ignore_errors: true

    - name: Install postman
      homebrew:
        name: postman
        state: present
      ignore_errors: true

    - name: Install slack
      homebrew:
        name: slack
        state: present
      ignore_errors: true

    - name: Install spotify
      homebrew:
        name: spotify
        state: present
      ignore_errors: true

    - name: Install vlc
      homebrew:
        name: vlc
        state: present
      ignore_errors: true

    - name: Install vscode
      homebrew:
        name: visual-studio-code
        state: present
      ignore_errors: true